services:
  api:
    build: .
    container_name: api_curriculos
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_started
    networks:
      - backend
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/curriculos
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    environment:
      - MONGO_INITDB_DATABASE=curriculos

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
